AMS-6006 added topstory, priority & mod_pubdate into push to redfact
atex-community-plugins/camel-post-to-redfact pull request #28
Opened 2023-05-11 08:31 UTC by leighfwarren

2023-05-18 08:32 UTC, prabjohns-atex requested changes
Adding a dependency on adm binary will cause circular dependency issues at some point. Would be better to use reflection to get what you need.

2023-05-18 08:32 UTC, prabjohns-atex commented on pom.xml
> +  <version>1.0-SNAPSHOT</version>
why is this 1.0 ?

2023-05-18 08:32 UTC, prabjohns-atex commented on pom.xml
> +    <version>11.0.0-fp2</version>
why change this ?

2023-05-18 08:32 UTC, prabjohns-atex commented on pom.xml
> +    <polopoly.version>11.0.0-fp2</polopoly.version>
this will be a problem too

2023-05-18 08:32 UTC, prabjohns-atex commented on pom.xml
> +            <version>2.6</version>
why change this ?

2023-05-18 08:32 UTC, prabjohns-atex commented on src/main/java/com/atex/onecms/app/dam/integration/camel/component/redfact/RedFactUtils.java
> +    public List<NameValuePair> convertArticleToForm(ContentResult<CustomArticleBean> source, CustomArticleBean damArticle) {
can we use reflection instead ? Adding a dependancy on adm-binary will cause a problem.

2023-05-18 08:32 UTC, prabjohns-atex commented on src/main/java/com/atex/onecms/app/dam/integration/camel/component/redfact/RedFactUtils.java
> +        Map<String, Map<String,String>> propertyBag = damArticle.getPropertyBag();
get via reflection

2023-05-19 10:52 UTC, leighfwarren commented on src/main/java/com/atex/onecms/app/dam/integration/camel/component/redfact/RedFactUtils.java
> +    public List<NameValuePair> convertArticleToForm(ContentResult<CustomArticleBean> source, CustomArticleBean damArticle) {
i have used reflection in the new commit

2023-05-19 10:52 UTC, leighfwarren commented on src/main/java/com/atex/onecms/app/dam/integration/camel/component/redfact/RedFactUtils.java
> +        Map<String, Map<String,String>> propertyBag = damArticle.getPropertyBag();
done

2023-05-19 12:29 UTC, closed without merging